= Ong Eden - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: JelphaBot

'''

== Overview

JelphaBot is a desktop application that serves as a simple yet comprehensive task manager for NUS students.
Interactions with the application and commands are entered through CLI. For a better user experience, JavaFX was used to create and enhance the GUI.

== Summary of contributions

* *Major enhancement*: added *the ability for users to have a summary view of their tasks due and completed within the day*.
** What it does: allows the user to have a simplified view of all the tasks that are due to be completed within the day, as well as the tasks that the user have completed within the day, under one page. This page is shown upon the startup of the application, and can be accessed anytime
while using the app by entering the `summary` command.
** Justification: In the event the user wishes to have a quick look at what tasks he/she has remaining to complete within the day, or to see what tasks he/she has completed
within the day, the user can easily do so and view this information all under the same page, with just a single command.
This feature improves the product significantly with the convenience that it provides to the user in obtaining a quick but comprehensive overview of the above-mentioned tasks.
** Highlights:
*** This enhancement works with existing commands and commands to be added in future. It required an in-depth analysis of design alternatives so as to determine the optimal layout of the UI of the Summary panel to enhance the user experience as much as possible.
*** The implementation too was challenging as it required the creation of special predicates to filter the tasks in the user's task list to be displayed, as well as deciding on what information from the tasks to display to the users.  Eventually, I decided to display only the Module Code and the Description of the task.
*** Another challenge during the implementation was ensuring that the tasks that were completed within the day were still displayed when the user exits the application, and starts it again within the same day. This required extra data to be stored and hence required modification of classes in `Storage` to ensure that
the data was stored correctly.
** Relevant pull requests:
https://github.com/AY1920S2-CS2103T-F09-2/main/pull/71[#71],
https://github.com/AY1920S2-CS2103T-F09-2/main/pull/80[#80],
https://github.com/AY1920S2-CS2103T-F09-2/main/pull/170[#170],
https://github.com/AY1920S2-CS2103T-F09-2/main/pull/172[#172],
https://github.com/AY1920S2-CS2103T-F09-2/main/pull/230[#230]
https://github.com/AY1920S2-CS2103T-F09-2/main/pull/243[#243]
** Credits: The structure and the classes in the summary package (under `Model`) were inspired by that of the productivity package, which is under `Model` as well.
* *Minor enhancement*: added a `done` command that allows the user to mark a task with the given index as completed.

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=delete]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=undoredo]


== PROJECT: PowerPointLabs

'''

_{Optionally, you may include other projects in your portfolio.}_
